
# Hier kann der algemeine preis fetsgelegt werden pro GS-Block
buypricePerBlock: 10.0
sellpricePerBlock: 5.0


# Füge hier deine Weltene hinzu, in den es erlaubt ist Grundstück zu erstellen.
allowed-worlds:
  - world
  - world_nether
  - custom_world